### ISSUE TITLE
Error messages when creating ARGO program in Platform but program gets created 

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/program-service#365] opened 2021-11-22 21:56 UTC
## Describe the bug
An error is generated when trying to create a program at https://platform.icgc-argo.org/submission/program/create, but the program does actually get created. This error is similar to https://github.com/icgc-argo/program-service/issues/362 (it gives the same error initially). Not sure if program got created correctly and if Program Administrator received the invitation email.

## Steps to Reproduce
Enter details about program at https://platform.icgc-argo.org/submission/program/create and click on "Create". This gives the following error (`Something went wrong, please try again later or contact us for assistance`):

![click_first_time](https://user-images.githubusercontent.com/4992044/142939803-0920c42b-e9d8-4f64-9659-8f10af2063e4.jpg)

Click on "Create" button second time and it returns a different error indicating the program was already created, even though it gave an error initially (`Program Not Created. A program with the same Program Short Name already exists. Please choose a new Program Short Name`):

![click_second_time](https://user-images.githubusercontent.com/4992044/142939814-370ddff0-8a78-400b-8964-662d0e5b183e.jpg)

The program list at https://platform.icgc-argo.org/submission/program shows the new program was created (`MONSTAR-JP`):
![program_list](https://user-images.githubusercontent.com/4992044/142939821-e5f0d335-1c08-4925-ac51-325d988c691c.jpg)

**Comment by blabadi** [comment] 2021-11-22 22:13
Update1: 

the error doesn't seem to have happened in program service, I see success log there and no exceptions
```
2021-11-22 21:37:50.413 DEBUG 1 --- [lt-executor-164] o.i.a.p.services.ProgramServiceFacade    : Created MONSTAR-JP
```

**Comment by blabadi** [comment] 2021-11-24 16:28
Couldn't reproduce the first error after creating few programs in QA, used random and same data, the second error is correct given that the program was created successfully.
no other trace for errors found in gateway or UI logs (could be lack of logs in gateway).

since this is not a program service issue as it seems, will close this

**Closed** 2021-11-24 16:29 UTC
Labels: bug
